### ISSUE TITLE
retour info volume sur les player

### ISSUE THREAD

**Issue by canabang** [sigalou/jeedom_alexaapi#58]
ajouter le retour d'info volume sur les player comme ca existe sur les device (echo)

**Comment by sigalou** [comment]
J'ai bien le "volume info" sur mes players
![image](https://user-images.githubusercontent.com/26350534/107851558-3488ac80-6e0b-11eb-9221-36023e150b5f.png)

Sur quel plugin tu le veux ?

**Comment by canabang** [comment]
alors c'est sur les player "groupe" qu'il ne doit pas y etre

**Comment by canabang** [comment]
dans le plugin deezer pour moi mais ca doit etre la meme partout

**Comment by sigalou** [comment]
Sur les groupes, on n'a pas l'info. Raison pour laquelle on ne l'a pas dans le player mais on ne l'a pas plus dans le device.
